### ISSUE TITLE
SD card use: burning ESP32 efuses, or feasible with correct passthru?

### ISSUE THREAD

**Issue by bluesceada** [emard/ulx3s-passthru#3]
In https://github.com/emard/ulx3s-bin it is suggested to burn the efuses of the ESP32 to fix the flash voltage to 3.3V, which is permanent. I wonder if that is really necessary, or if it can stay flexible, which might be beneficial for something (for example, would it save more power?).
It seems before 8e92436 , 22e3f75 and 9b5ff09 it was tried to do it with this passthru bitstream by pulling sd_d(2) to GND at the right time, but which was unreliable and thus removed again.

Is it definitely impossible to work reliably, or could it work? Then me or someone else could take a closer look again.

**Comment by emard** [comment]
burning this fuse fixes esp32 internal flash voltage to 1.8V/3.3V
and this flash needs 3.3V (and won't work for 1.8V) so unless you
(or them :) change internal flash chip, all should be ok with fuse burnt

if fuse in unburn, everything should be ok too if you don't put SD card.

power on state of gpio12 selects flash voltage
and you may have problem ESP32 not booting with some SD cards
that pull or respond somehow to gpio12

**Comment by bluesceada** [comment]
Thanks for clarifying. So for any ESP32-WROOM-32(D) the flash inside the module is 3.3V(is it?), and we should burn the efuse, which isn't done by Espressif already (instead their datasheet says MTDI/GPIO12 should be pulled low during startup).

**Comment by emard** [comment]
When I was investigating this, about a year ago
espressif stated flash chip voltage

esp32 wroom with 3.3V flash
esp32 wrover with 1.8V flash

modules come shipped without burning this fuse.

**Comment by bluesceada** [comment]
Thanks. Yes I got a ESP32-WROOM-32D (new revision of the wroom), because of that I was also skeptical, but from what I found, it also has a 3.3V flash.

**Comment by emard** [comment]
I recommend to obtain the ESP32 programmer socket adapter
in which you can plug ESP32 without soldering and try anything,
programming and fuses, even If you brick it, it's only 3$ of waste
